name: cipher
version: 0.7.1
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library implementing cryptographic algorithms.
homepage: http://izaera.github.io/cipher/
documentation: http://izaera.github.io/cipher/api/
dependencies:
  bignum: '>=0.0.5 <0.1.0'
  fixnum: '>=0.9.0 <0.10.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
